project: MAIN
var: NPV
scale: !!float 1e-6 # M€/€, float flag needed

plot:
  name: "NPV"
  save: true
  show: true
  # width: 8.5
  height: 9
  autoscale: false

  y1:
    min: 0
    max: 15
    pad: 0
    major_ticks: {start: 0, stop: 15, step: 3.0}
    minor_ticks: {start: 0, stop: 15, step: 1.5}
    major_grid: true
    minor_grid: false
    label: "Lifetime NPV\n(M€)"
    label_kwargs: {fontweight: "bold"}
    ticklabel_format: "{:.0f}"
